name: Echoplay
title: Echoplay | Έλα να παίξουμε μαζί!
description: Το Echoplay είναι ένας ιστότοπος όπου βρισκόμαστε για να παίξουμε, να συζητήσουμε και να διασκεδάσουμε! Από τη Νικολέττα Χαλδαιοπούλου.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Αρχική
    url: /
  - title: Σχετικά
    url: /about
  - title: Επικονωνία
    url: /contact
  - title: Ροή
    url: /feed.xml
email: n.chaldeopoulou@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
